spring.application.name=ecom-proj

spring.datasource.url=jdbc:mysql://database-1.cy76ga6a49cu.us-east-1.rds.amazonaws.com:3306/ecommerce
spring.datasource.username=admin
spring.datasource.password=Yogendra12
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
